dotenv added

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,7 +1,7 @@
 name: Continuous Integration
 
 on: 
-- push
+- pull_request
 
 jobs:
   testing:
@@ -14,37 +14,40 @@ jobs:
       - name: install dependencies
         run: pip install pytest
 
+      - name: install package
+        run: pip install dotenv
+
       - name: test
         run: python -m pytest -v
   
-  lint-and-format:
-    runs-on: ubuntu-latest
+  # lint-and-format:
+  #   runs-on: ubuntu-latest
 
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #     with:
+  #       fetch-depth: 0
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.8
+  #   - name: Set up Python
+  #     uses: actions/setup-python@v2
+  #     with:
+  #       python-version: 3.8
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install flake8 black
+  #   - name: Install dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       pip install flake8 black
 
-    - name: Lint with flake8
-      run: |
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || echo "Linting failed, proceeding to formatting..."
+  #   - name: Lint with flake8
+  #     run: |
+  #       flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || echo "Linting failed, proceeding to formatting..."
 
-    - name: Format code with black
-      run: |
-        black .
+  #   - name: Format code with black
+  #     run: |
+  #       black .
 
-    - name: Commit changes
-      run: |
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git diff --exit-code && echo "No formatting changes to commit." || (git commit -am "Format code" && git push)
+  #   - name: Commit changes
+  #     run: |
+  #       git config --local user.email "action@github.com"
+  #       git config --local user.name "GitHub Action"
+  #       git diff --exit-code && echo "No formatting changes to commit." || (git commit -am "Format code" && git push)
